services:
  web:
    build: .
    container_name: nette-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: nette-db
    environment:
      MYSQL_ROOT_PASSWORD: heslo
      MYSQL_DATABASE: vloln1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nette-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: heslo
    ports:
      - "8081:80"

volumes:
  db_data:
